# Generated by Django 3.1.3 on 2020-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
    ]
