# Generated by Django 3.1.3 on 2020-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201118_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Дислайк'),
        ),
    ]
