# Generated by Django 3.1.3 on 2020-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201123_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default='test_tag', verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
