# Generated by Django 3.1.3 on 2020-11-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20201124_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=24, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': ' Тэг ',
                'verbose_name_plural': ' Тэги',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.tag', verbose_name='Тег'),
        ),
    ]
