# Generated by Django 3.1.3 on 2020-11-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default=None, verbose_name='Тег'),
        ),
    ]
