# Generated by Django 3.1.3 on 2020-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20201125_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=24, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': ' Тэг ',
                'verbose_name_plural': ' Тэги',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
