# Generated by Django 3.1.3 on 2020-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20201125_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='post.Tag', verbose_name='Тег'),
        ),
    ]
