# Generated by Django 3.1.3 on 2020-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20201125_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=24, verbose_name='Категория')),
            ],
            options={
                'verbose_name': ' Категория ',
                'verbose_name_plural': ' Категории ',
            },
        ),
    ]
