# Generated by Django 3.1.3 on 2020-11-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='post.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': ' Рейтинг ',
                'verbose_name_plural': ' Рейтинг ',
            },
        ),
    ]
