# Generated by Django 3.1.3 on 2020-11-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
