# Generated by Django 3.1.3 on 2020-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.ProductCategory', verbose_name='Категория'),
        ),
    ]
